### ISSUE TITLE
А для яндекса можете?

### ISSUE THREAD

**Issue by Nashev** [sfsef/uBlacklist-subscription#1]
В гугле как-то не особо достают, а в Яндекс-поиске прям засилье какое-то! ((

**Comment by Nashev** [comment]
В гитхабе у расширения для гугла есть запрос https://github.com/iorate/uBlacklist/issues/91 на поддержку яндекса, но он без ответа...

**Comment by sfsef** [comment]
Смотрю расширение обновилось и поддерживает Яндекс. Проверил блеклист выборочно, сайты до сих пор живые
