### ISSUE TITLE
Расширение для хрома заблокировано гуглом

### ISSUE THREAD

**Issue by Nashev** [sfsef/uBlacklist-subscription#2]
https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe не даёт установить ((

зарегал им https://github.com/iorate/uBlacklist/issues/114

**Comment by sfsef** [comment]
https://github.com/iorate/uBlacklist/releases

Можно скачать релиз с официального репозитория. Надеюсь, что расширение появится в интернет-магазине Chrome
